### ISSUE TITLE
[TODO] work on improving server and backend and db

### ISSUE THREAD

**Issue by gbowne1** [gbowne1/fashion-marketplace#4]
I have created a /src/server.js however several things need to be done:

- [ ] Set up express
- [ ] Make the initial routes
      Including 404 Not Found and the root route /.
- [ ] Set up middleware
- [ ] set up routers 
- [ ] Make logs with Morgan & Winston
- [ ] set up helmet and cors for XSS, XHR, etc.
- [ ] set up bcrypt, axios, passport, jwt for login and logout functionality.

Improve the backend and database by adding:

- [ ] an example .variable.env with the port number and mongodb connection string.
- [ ] ensure that can be consumed by MongoDB Atlas, Compass and also mongod, mongo, mongosh, mongoose.
- [ ] Create a utility that creates a test user in the user collection of the database 

The database will be called fashionmarket.
I have installed the most commonly used packages to the server package.json file
