### ISSUE TITLE
[TODO] Design the page theme

### ISSUE THREAD

**Issue by gbowne1** [gbowne1/fashion-marketplace#9]
Other than the color I added to the navbar, some color theming needs to be done,

- [ ] Fix the theme switch
- [ ] Locate and use some complimentary feminine colors to go along with the navbar color
- [ ] If we also use dark mode, we should implement font colors for dark, maybe?
